CREATE TABLE IF NOT EXISTS staff_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'call-agent' CHECK (role IN ('admin', 'call-agent', 'contact-generator')),
  approved BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE staff_users ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE TABLE IF NOT EXISTS daily_calls (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  call_order BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  business_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  staff_id UUID NOT NULL REFERENCES staff_users(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'interested', 'no-answer', 'not-interested')),
  notes TEXT NOT NULL DEFAULT '',
  work_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE daily_calls ADD COLUMN IF NOT EXISTS call_order BIGINT GENERATED BY DEFAULT AS IDENTITY;
CREATE INDEX IF NOT EXISTS daily_calls_staff_day_idx ON daily_calls (staff_id, work_date);
CREATE INDEX IF NOT EXISTS daily_calls_day_idx ON daily_calls (work_date);
CREATE INDEX IF NOT EXISTS daily_calls_order_idx ON daily_calls (work_date, call_order);

CREATE TABLE IF NOT EXISTS daily_shifts (
  staff_id UUID NOT NULL REFERENCES staff_users(id) ON DELETE CASCADE,
  work_date DATE NOT NULL DEFAULT CURRENT_DATE,
  elapsed_seconds INTEGER NOT NULL DEFAULT 0 CHECK (elapsed_seconds >= 0),
  clocked_in_at TIMESTAMPTZ,
  signed_out_at TIMESTAMPTZ,
  PRIMARY KEY (staff_id, work_date)
);

CREATE TABLE IF NOT EXISTS generated_contacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id UUID NOT NULL,
  business_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  area TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  map_query TEXT NOT NULL DEFAULT '',
  generator_id UUID NOT NULL REFERENCES staff_users(id) ON DELETE CASCADE,
  work_date DATE NOT NULL DEFAULT CURRENT_DATE,
  approved_at TIMESTAMPTZ,
  assigned_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE generated_contacts ADD COLUMN IF NOT EXISTS submission_id UUID;
ALTER TABLE generated_contacts ADD COLUMN IF NOT EXISTS approved_at TIMESTAMPTZ;
ALTER TABLE generated_contacts ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS generated_contacts_day_idx ON generated_contacts (work_date);
CREATE INDEX IF NOT EXISTS generated_contacts_generator_day_idx ON generated_contacts (generator_id, work_date);
CREATE INDEX IF NOT EXISTS generated_contacts_submission_idx ON generated_contacts (work_date, submission_id)
  WHERE approved_at IS NULL AND submission_id IS NOT NULL;
